import Head from 'next/head';
import Link from 'next/link';

function App() {
	return (
		<>
			<Head>
				<title>dot.gg</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
				<Link href='/Detail'>asd</Link>
			</Head>
		</>
	);
}

export default App;
